export const GET_VALUE = 'GET_VALUE';

export const ON_SIGN_UP = 'ON_SIGN_UP';
export const ON_SIGN_UP_FULFILLED = 'ON_SIGN_UP_FULFILLED';
export const ON_SIGN_UP_REJECTED = 'ON_SIGN_UP_REJECTED';
export const ON_SIGN_UP_PENDING = 'ON_SIGN_UP_PENDING';

export const ON_SIGNIN = 'ON_SIGNIN';
export const ON_SIGNIN_FULFILLED = 'ON_SIGNIN_FULFILLED';
export const ON_SIGNIN_REJECTED = 'ON_SIGNIN_REJECTED';
export const ON_SIGNIN_PENDING = 'ON_SIGNIN_PENDING';

export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_CURRENT_LOCATION_FULFILLED = 'GET_CURRENT_LOCATION_FULFILLED';
export const GET_CURRENT_LOCATION_REJECTED = 'GET_CURRENT_LOCATION_REJECTED';

export const FETCH_GITHUB_PROFILE = 'FETCH_GITHUB_PROFILE';
export const FETCH_GITHUB_PROFILE_FULFILLED = 'FETCH_GITHUB_PROFILE_FULFILLED';
export const FETCH_GITHUB_PROFILE_REJECTED = 'FETCH_GITHUB_PROFILE_REJECTED';

export const FETCH_GITHUB_USER_ACCOUNT = 'FETCH_GITHUB_USER_ACCOUNT';
export const FETCH_GITHUB_USER_ACCOUNT_FULFILLED = 'FETCH_GITHUB_USER_ACCOUNT_FULFILLED';
export const FETCH_GITHUB_USER_ACCOUNT_REJECTED = 'FETCH_GITHUB_USER_ACCOUNT_REJECTED';

export const REVIEW_AND_CONFIRM = 'REVIEW_AND_CONFIRM';
export const REVIEW_AND_CONFIRM_FULFILLED = 'REVIEW_AND_CONFIRM_FULFILLED';
export const REVIEW_AND_CONFIRM_PENDING = 'REVIEW_AND_CONFIRM_PENDING';
export const REVIEW_AND_CONFIRM_REJECTED = 'REVIEW_AND_CONFIRM_REJECTED';

export const FETCH_EVENT_BRITE_EVENTS = 'FETCH_EVENT_BRITE_EVENTS';
export const FETCH_EVENT_BRITE_EVENTS_PENDING = 'FETCH_EVENT_BRITE_EVENTS_PENDING';
export const FETCH_EVENT_BRITE_EVENTS_FULFILLED = 'FETCH_EVENT_BRITE_EVENTS_FULFILLED';
export const FETCH_EVENT_BRITE_EVENTS_REJECTED = 'FETCH_EVENT_BRITE_EVENTS_REJECTED';


export const GET_VENUS_BY_ID = 'GET_VENUS_BY_ID';
export const GET_VENUS_BY_ID_FULFILLED = 'GET_VENUS_BY_ID_FULFILLED';
export const GET_VENUS_BY_ID_REJECTED = 'GET_VENUS_BY_ID_REJECTED';

export const GET_CURRENT_EVENT = 'GET_CURRENT_EVENT';
export const GET_CURRENT_EVENT_FULFILLED = 'GET_CURRENT_EVENT_FULFILLED';