export const GET_VALUE = 'GET_VALUE';
export const ON_SIGN_UP = 'ON_SIGN_UP';
export const ON_SIGNIN = 'ON_SIGNIN';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_CURRENT_LOCATION_FULFILLED = 'GET_CURRENT_LOCATION_FULFILLED';
export const FETCH_GITHUB_PROFILE = 'FETCH_GITHUB_PROFILE';
export const FETCH_GITHUB_USER_ACCOUNT = 'FETCH_GITHUB_USER_ACCOUNT';
export const FETCH_GITHUB_PROFILE_FULFILLED = 'FETCH_GITHUB_PROFILE_FULFILLED';
export const FETCH_GITHUB_USER_ACCOUNT_FULFILLED = 'FETCH_GITHUB_USER_ACCOUNT_FULFILLED';
export const REVIEW_AND_CONFIRM = 'REVIEW_AND_CONFIRM';

export const FETCH_EVENT_BRITE_EVENTS = 'FETCH_EVENT_BRITE_EVENTS';
export const FETCH_EVENT_BRITE_EVENTS_FULFILLED = 'FETCH_EVENT_BRITE_EVENTS_FULFILLED';


export const GET_VENUS_BY_ID = 'GET_VENUS_BY_ID';
export const GET_VENUS_BY_ID_FULFILLED = 'GET_VENUS_BY_ID_FULFILLED';
export const FETCH_EVENT_BRITE_EVENTS_PENDING = 'FETCH_EVENT_BRITE_EVENTS_PENDING';